branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: udagram-api-dev
deploy:
  artifact: www/Archive.zip
global:
  application_name: udagram-api
  branch: null
  default_ec2_keyname: aws-eb-keypair
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
