version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: "cimg/node:16.13.2"
    steps:
      - browser-tools/install-browser-tools
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install dependencies
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install dependencies
          command: |
            npm run backend:install 
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      - run:
          name: frontend deploy 
          command: |
            npm run frontend:deploy
      - run:
          name: backend deploy 
          command: |
            npm run backend:deploy
      - run:
          name: deploy env variables  
          command: |
            eb setenv DB_PORT=$5432 JWT_SECRET=$"hello_ther" PORT=$80 POSTGRES_HOST=$ POSTGRES_PASSWORD=$postgres POSTGRES_USERNAME=postgres